name: Deploy Next.js Site to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          set -e
          printf "Installing dependencies...\n"
          npm install --legacy-peer-deps

      - name: Build project
        run: |
          set -e
          printf "Building project...\n"
          npm run build

      - name: Set up SSH
        run: |
          set -e
          printf "Setting up SSH...\n"
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Upload build to the server
        run: |
          set -e
          printf "Uploading new build to server...\n"
          scp -i ~/.ssh/id_ed25519 -r build/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.DEPLOY_PATH }}